#line 1 "src/docmark_token_lexers.c"
	#include "docmark_token_lexers.h"

	#include "docmark_debug.h"
	#include "docmark_definitions.h"

	#include <stdlib.h>
	#include <stdio.h>
	#include <string.h>

	// FLAGS
	unsigned int heading_rank = 0;
	int in_left_column = 0;
	int in_right_column = 0;

	Token *current_token;
	int LAST_CONDITION = 0;
	int buffer_counter = 0;
	size_t buffer_size = 0;
	char *buffer = NULL;

	static void flush_buffer_raw() {
		if (buffer) {
			add_child(RAW_DATA, buffer, NULL, 0, current_token);
			buffer_counter = 0;
			buffer[buffer_counter] = '\0';
		}
	}
	
	static void flush_buffer_paragraph() {
		char* buffer_pointer = buffer;
		if (buffer) {
			if (strlen(buffer_pointer) > 1) {
				if (*buffer_pointer == ' ' || *buffer_pointer == '\t') {
					while(*buffer_pointer == ' ' || *buffer_pointer == '\t') {
						++buffer_pointer;
					}
					add_child(INDENTED_PARAGRAPH, buffer_pointer, NULL, 0, current_token);
				}
				else {
					add_child(PARAGRAPH, buffer, NULL, 0, current_token);
				}
			}
			buffer_counter = 0;
			buffer[buffer_counter] = '\0';
		}
	}

#line 49 "src/docmark_token_lexers.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 39
#define YY_END_OF_BUFFER 40
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[290] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   40,   37,   38,   35,
       36,   35,   35,   35,   35,   35,   35,   35,   35,    1,
        2,    1,    1,    1,    1,    1,    1,    1,    1,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,

       35,   35,   35,   35,   35,   37,    6,   31,   37,   37,
        0,    0,    4,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    6,   30,    0,   29,
        0,    0,    0,    0,    0,   23,    0,    0,    0,    0,
       21,   32,   27,    0,   34,   33,    0,    0,    7,    0,
        0,    9,    0,    0,   13,    0,    0,   15,    0,    0,
       17,    0,    0,   19,    0,    0,   25,    0,    0,   11,

        0,    0,    7,    0,    0,    9,    0,    0,   15,    0,
        0,   17,    0,    0,   19,    0,    0,   25,    0,    0,
       11,    0,   28,    0,    0,    0,    0,    0,    3,    0,
        0,   22,    0,    8,   10,   14,   16,   18,   20,   26,
       12,    8,   10,   16,   18,   20,   26,   12,    0,    0,
        0,    0,   24,    0,    0,    0,   23,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   22,    0,    0,    0,    0,    0,   21,    5,
        0,    0,    0,    0,    0,    0,    0,   22,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    1,    6,    1,    1,    1,    1,    1,
        1,    7,    8,    1,    9,   10,    1,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,    1,    1,
       13,   14,    1,    1,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       16,   17,   18,   19,   20,   21,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   22,   23,   24,   25,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[26] =
    {   0,
        1,    2,    3,    2,    2,    1,    4,    5,    6,    1,
        1,    1,    7,    1,    1,    1,    1,    1,    8,    9,
       10,    1,    1,    1,   11
    } ;

static const flex_int16_t yy_base[337] =
    {   0,
      434,  433,  432,    0,   23,   46,  431,  430,  429,  428,
      427,  424,  421,  419,  418,  417,  416,  415,  414,  413,
      412,  411,   69,   89,  410,  409,  406,  403,  402,  401,
      399,  398,  397,  396,  395,  394,  393,  390,  387,  386,
      385,  383,  382,  381,  380,  379,  378,  377,  374,  371,
        0,    0,  370,  369,  368,  367,  366,  365,  363,  362,
      358,  354,  345,   24,  342,  339,  341, 1472, 1472, 1472,
     1472,  337,  113,   32,   36,  118,   35,   30,   57, 1472,
     1472,  321,  312,  309,  308,  307,  305,  296,  293,  291,
      287,  283,  280,  277,  275,  271,  267,  131,  147,   68,

      163,  179,  197,  216,  236,   59, 1472,  278,  274,   47,
      270,  257,   81,  260,   98,  255,  122,   96,  126,  265,
      257,   76,  256,  254,  278,  294,  310,  326,  342,  358,
      374,  390,  406,  424,  442,  461,  480,  500,  520,  544,
      568,  584,  600,  616,  632,  648,  664,  682,  700,  719,
      738,  758,  778,  802,  137,  826, 1472, 1472,  247, 1472,
      245,  139,  847,  241,  151,  168,   26,  155,  232,  169,
       99,  222,  219,  175,  217,  204,  208,    0,    0,  204,
        0,    0,  198,    0,    0,  192,    0,    0,  168,    0,
        0,  165,    0,    0,  158,    0,    0,  150,    0,    0,

      162,    0,    0,  155,    0,    0,  149,    0,    0,  118,
        0,    0,  110,    0,    0,  105,    0,    0,   97,    0,
        0,  852, 1472,  186,  866,  190,  112,  141, 1472,  101,
      201,  871,  208,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  882,  903,
       90,  206,   80,  926,   78,  221,  223,  142,  240,  244,
       69,   46,  249,  931,    0,  253,   66,  269,  273,  284,
       60,  288,  225,  156,  300,  192,   49,  304,   26, 1472,
      314,  318,  330,  334,  347,   25,  351,  353, 1472,  955,
      966,  977,  988,  999, 1010, 1021, 1032, 1043, 1054, 1065,

     1076, 1087, 1098, 1108, 1119, 1130, 1141, 1152, 1163, 1174,
     1185, 1196, 1207, 1218, 1229, 1240, 1251, 1262, 1273, 1284,
     1295, 1306, 1317, 1328, 1339, 1350, 1361, 1372, 1383, 1394,
     1405, 1416, 1427, 1438, 1449, 1460
    } ;

static const flex_int16_t yy_def[337] =
    {   0,
      290,  290,  291,  289,  292,  292,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  291,    4,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
        6,    6,  290,  290,  290,  290,  293,  293,  290,  290,
      290,  290,  290,  294,  290,  290,  289,  289,  289,  289,
      289,  295,  295,  289,  295,  295,  295,  295,  295,  289,
      289,  296,  297,  298,  299,  300,  301,  302,  303,  296,
      297,  298,  299,  300,  301,  302,  303,  304,  305,  298,

      306,  307,  308,  309,  310,  311,  289,  289,  312,  312,
      295,  289,  295,  295,  313,  289,  295,  295,  314,  295,
      295,  295,  295,  295,  315,  315,  316,  316,  317,  317,
      318,  318,  319,  319,  320,  320,  321,  321,  322,  322,
      323,  323,  324,  324,  325,  325,  326,  326,  327,  327,
      328,  328,  329,  329,  311,  311,  289,  289,  312,  289,
      312,  289,  295,  313,  313,  289,  289,  330,  314,  314,
      289,  289,  289,  295,  289,  289,  126,  126,  126,  128,
      128,  128,  130,  130,  130,  132,  132,  132,  134,  134,
      134,  136,  136,  136,  138,  138,  138,  140,  140,  140,

      142,  142,  142,  144,  144,  144,  146,  146,  146,  148,
      148,  148,  150,  150,  150,  152,  152,  152,  154,  154,
      154,  311,  289,  331,  295,  332,  289,  289,  289,  330,
      330,  289,  289,  126,  128,  130,  132,  134,  136,  138,
      140,  142,  144,  146,  148,  150,  152,  154,  311,  311,
      331,  331,  333,  295,  332,  332,  289,  332,  332,  334,
      289,  289,  335,  249,  250,  311,  295,  295,  332,  332,
      334,  334,  289,  334,  334,  289,  335,  335,  289,  289,
      332,  334,  334,  336,  334,  336,  336,  289,    0,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,

      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289
    } ;

static const flex_int16_t yy_nxt[1498] =
    {   0,
       72,   70,   71,   70,   70,   73,   72,   72,   74,   72,
       75,   70,   72,   76,   72,   77,   72,   72,   72,   72,
       78,   72,   79,   72,   72,   81,  108,  288,  229,   82,
       83,   84,  112,  115,  167,   85,  115,  112,  112,  233,
      116,   86,   87,   88,  110,  117,  118,   89,   81,  160,
      122,  279,   82,   83,   84,  276,  262,  121,   85,  112,
      156,  157,  273,  156,   86,   87,   88,  161,  112,  115,
       89,   71,  115,  275,  123,   90,   91,   92,  173,  124,
      257,   93,  113,  112,  130,  113,  174,   94,   95,   96,
      174,  162,  253,   97,   72,   98,   99,  100,  112,  165,

      166,  101,  165,  232,   72,  117,  118,  102,  103,  104,
      162,   72,  233,  105,  113,  112,  259,  113,  114,  119,
      112,  248,  119,  168,  112,  247,  168,  170,  171,  246,
      170,  120,  111,  112,  111,  111,  245,  111,  156,  157,
      224,  156,  115,  224,  257,  115,  269,  142,  111,  112,
      111,  111,  165,  166,  111,  165,  231,  232,  273,  231,
      282,  244,  243,  144,  111,  112,  111,  111,  242,  226,
      170,  171,  227,  170,  241,  111,  228,  173,  240,  146,
      111,  112,  111,  111,  239,  174,  238,  252,  253,  174,
      252,  256,  257,  284,  258,  148,  284,  111,  111,  112,

      111,  111,  231,  232,  237,  231,  236,  252,  253,  263,
      252,  235,  263,  150,  234,  162,  111,  111,  112,  111,
      111,  233,  256,  257,  226,  258,  260,  227,  162,  261,
      162,  228,  152,  162,  171,  262,  111,  111,  112,  111,
      111,  256,  257,  166,  270,  272,  273,  223,  274,  160,
      278,  279,  154,  278,  156,  280,  176,  156,  175,  172,
      111,  113,  112,  167,  113,  163,  119,  112,  162,  119,
      113,  112,  112,  113,  256,  257,  160,  270,  120,  178,
      158,  178,  178,  140,  179,  256,  257,  138,  281,  272,
      273,  136,  274,  134,  178,  178,  132,  178,  178,  130,

      178,  272,  273,  128,  283,  278,  279,  126,  278,  140,
      178,  181,  138,  181,  181,  256,  257,  182,  281,  272,
      273,  136,  283,  134,  132,  130,  181,  181,  128,  181,
      181,  272,  273,  181,  285,  287,  288,  126,  287,  112,
      289,   69,  181,  184,   69,  184,  184,  108,  272,  273,
      185,  285,  287,  288,  260,  287,   69,  261,  184,  184,
       69,  184,  184,  262,   69,   69,  184,  107,  107,   69,
       69,   69,   69,   69,  184,  187,   69,  187,  187,   69,
       69,   69,   69,   69,   69,   69,  188,   69,   69,   69,
      187,  187,   69,  187,  187,   69,   69,   69,   69,   69,

       69,   69,  187,   69,   69,   69,  187,  190,   69,  190,
      190,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,  190,   69,  191,  190,   69,  190,  190,   69,
       69,   69,   69,   69,   71,   69,   69,  289,  289,  289,
      190,  289,  190,  193,  289,  193,  193,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  193,  289,
      289,  194,  193,  289,  193,  193,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  193,  289,  289,
      193,  196,  289,  196,  196,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  196,  289,  289,  289,

      197,  196,  289,  196,  196,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  196,  289,  289,  289,
      196,  199,  289,  199,  199,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  199,  289,  289,  289,
      289,  289,  289,  289,  200,  199,  289,  199,  199,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      199,  289,  289,  289,  289,  289,  289,  289,  199,  202,
      112,  202,  202,  289,  203,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  202,  202,  112,  202,  202,  289,
      202,  289,  289,  289,  289,  289,  289,  289,  289,  289,

      202,  205,  112,  205,  205,  289,  289,  206,  289,  289,
      289,  289,  289,  289,  289,  289,  205,  205,  112,  205,
      205,  289,  289,  205,  289,  289,  289,  289,  289,  289,
      289,  289,  205,  208,  112,  208,  208,  289,  289,  289,
      289,  289,  289,  289,  209,  289,  289,  289,  208,  208,
      112,  208,  208,  289,  289,  289,  289,  289,  289,  289,
      208,  289,  289,  289,  208,  211,  112,  211,  211,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      211,  289,  212,  211,  112,  211,  211,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  211,  289,

      211,  214,  112,  214,  214,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  214,  289,  289,  215,
      214,  112,  214,  214,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  214,  289,  289,  214,  217,
      112,  217,  217,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  217,  289,  289,  289,  218,  217,
      112,  217,  217,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  217,  289,  289,  289,  217,  220,
      112,  220,  220,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  220,  289,  289,  289,  289,  289,

      289,  289,  221,  220,  112,  220,  220,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  220,  289,
      289,  289,  289,  289,  289,  289,  220,  156,  157,  289,
      156,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  222,  113,  112,
      289,  113,  225,  249,  157,  289,  249,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  250,  113,  112,  289,
      113,  254,  260,  289,  289,  261,  289,  289,  289,  289,
      289,  262,  162,  249,  157,  289,  249,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  250,  289,  289,  289,

      289,  289,  289,  222,  264,  157,  289,  264,  289,  289,
      289,  265,  265,  265,  265,  289,  289,  265,  289,  289,
      289,  289,  265,  289,  289,  289,  266,  113,  112,  289,
      113,  268,  264,  289,  289,  264,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  155,  289,  289,  289,  289,
      289,  289,  289,  289,  266,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  109,

      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  125,  289,  289,  289,  125,  125,  125,  125,  125,
      125,  125,  127,  289,  289,  127,  289,  127,  127,  127,
      127,  127,  127,  129,  289,  289,  129,  129,  289,  129,
      129,  129,  129,  129,  131,  289,  289,  131,  131,  131,
      289,  131,  131,  131,  131,  133,  289,  289,  133,  133,
      133,  133,  289,  133,  133,  133,  135,  289,  289,  135,
      135,  135,  135,  135,  289,  135,  135,  137,  289,  289,
      137,  137,  137,  137,  137,  137,  289,  137,  139,  289,

      289,  139,  139,  139,  139,  139,  139,  139,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  151,  151,  151,  151,  151,  151,  151,
      151,  151,  151,  151,  153,  153,  153,  153,  153,  153,
      153,  153,  153,  153,  153,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  159,  159,  159,  159,

      159,  159,  159,  159,  159,  159,  159,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  177,
      177,  289,  177,  177,  177,  177,  177,  177,  177,  177,
      180,  180,  289,  180,  180,  180,  180,  180,  180,  180,
      180,  183,  183,  289,  183,  183,  183,  183,  183,  183,
      183,  183,  186,  186,  289,  186,  186,  186,  186,  186,
      186,  186,  186,  189,  189,  289,  189,  189,  189,  189,
      189,  189,  189,  189,  192,  192,  289,  192,  192,  192,
      192,  192,  192,  192,  192,  195,  195,  289,  195,  195,

      195,  195,  195,  195,  195,  195,  198,  198,  289,  198,
      198,  198,  198,  198,  198,  198,  198,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  230,  230,  230,  230,  230,  230,

      230,  230,  230,  230,  230,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  267,  289,  289,
      267,  267,  289,  267,  267,  267,  267,  267,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,   67,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289

    } ;

static const flex_int16_t yy_chk[1498] =
    {   0,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    5,   64,  286,  167,    5,
        5,    5,   78,   74,  167,    5,   74,   77,   75,  279,
       74,    5,    5,    5,   64,   75,   75,    5,    6,  110,
       78,  277,    6,    6,    6,  262,  262,   77,    6,   79,
      106,  106,  271,  106,    6,    6,    6,  110,  267,  100,
        6,   23,  100,  261,   79,   23,   23,   23,  122,   79,
      255,   23,  113,  113,  100,  113,  122,   23,   23,   23,
      122,  253,  251,   23,   24,   24,   24,   24,  118,  115,

      115,   24,  115,  230,   24,  118,  118,   24,   24,   24,
      171,   24,  171,   24,   73,   73,  227,   73,   73,   76,
       76,  219,   76,  117,  117,  216,  117,  119,  119,  213,
      119,   76,   98,   98,   98,   98,  210,   98,  155,  155,
      162,  155,  228,  162,  258,  228,  258,   98,   99,   99,
       99,   99,  165,  165,   99,  165,  168,  168,  274,  168,
      274,  207,  204,   99,  101,  101,  101,  101,  201,  166,
      170,  170,  166,  170,  198,  101,  166,  174,  195,  101,
      102,  102,  102,  102,  192,  174,  189,  224,  224,  174,
      224,  226,  226,  276,  226,  102,  276,  102,  103,  103,

      103,  103,  231,  231,  186,  231,  183,  252,  252,  233,
      252,  180,  233,  103,  177,  176,  103,  104,  104,  104,
      104,  233,  256,  256,  257,  256,  273,  257,  175,  273,
      173,  257,  104,  172,  169,  273,  104,  105,  105,  105,
      105,  259,  259,  164,  259,  260,  260,  161,  260,  159,
      263,  263,  105,  263,  266,  266,  124,  266,  123,  121,
      105,  114,  114,  116,  114,  114,  120,  120,  112,  120,
      268,  268,  111,  268,  269,  269,  109,  269,  120,  125,
      108,  125,  125,   97,  125,  270,  270,   96,  270,  272,
      272,   95,  272,   94,  125,  126,   93,  126,  126,   92,

      126,  275,  275,   91,  275,  278,  278,   90,  278,   89,
      126,  127,   88,  127,  127,  281,  281,  127,  281,  282,
      282,   87,  282,   86,   85,   84,  127,  128,   83,  128,
      128,  283,  283,  128,  283,  284,  284,   82,  284,   72,
       67,   66,  128,  129,   65,  129,  129,   63,  285,  285,
      129,  285,  287,  287,  288,  287,   62,  288,  129,  130,
       61,  130,  130,  288,   60,   59,  130,   58,   57,   56,
       55,   54,   53,   50,  130,  131,   49,  131,  131,   48,
       47,   46,   45,   44,   43,   42,  131,   41,   40,   39,
      131,  132,   38,  132,  132,   37,   36,   35,   34,   33,

       32,   31,  132,   30,   29,   28,  132,  133,   27,  133,
      133,   26,   25,   22,   21,   20,   19,   18,   17,   16,
       15,   14,  133,   13,  133,  134,   12,  134,  134,   11,
       10,    9,    8,    7,    3,    2,    1,    0,    0,    0,
      134,    0,  134,  135,    0,  135,  135,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  135,    0,
        0,  135,  136,    0,  136,  136,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  136,    0,    0,
      136,  137,    0,  137,  137,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  137,    0,    0,    0,

      137,  138,    0,  138,  138,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  138,    0,    0,    0,
      138,  139,    0,  139,  139,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  139,    0,    0,    0,
        0,    0,    0,    0,  139,  140,    0,  140,  140,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      140,    0,    0,    0,    0,    0,    0,    0,  140,  141,
      141,  141,  141,    0,  141,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  141,  142,  142,  142,  142,    0,
      142,    0,    0,    0,    0,    0,    0,    0,    0,    0,

      142,  143,  143,  143,  143,    0,    0,  143,    0,    0,
        0,    0,    0,    0,    0,    0,  143,  144,  144,  144,
      144,    0,    0,  144,    0,    0,    0,    0,    0,    0,
        0,    0,  144,  145,  145,  145,  145,    0,    0,    0,
        0,    0,    0,    0,  145,    0,    0,    0,  145,  146,
      146,  146,  146,    0,    0,    0,    0,    0,    0,    0,
      146,    0,    0,    0,  146,  147,  147,  147,  147,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      147,    0,  147,  148,  148,  148,  148,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  148,    0,

      148,  149,  149,  149,  149,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  149,    0,    0,  149,
      150,  150,  150,  150,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  150,    0,    0,  150,  151,
      151,  151,  151,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  151,    0,    0,    0,  151,  152,
      152,  152,  152,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  152,    0,    0,    0,  152,  153,
      153,  153,  153,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  153,    0,    0,    0,    0,    0,

        0,    0,  153,  154,  154,  154,  154,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  154,    0,
        0,    0,    0,    0,    0,    0,  154,  156,  156,    0,
      156,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  156,  163,  163,
        0,  163,  163,  222,  222,    0,  222,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  222,  225,  225,    0,
      225,  225,  232,    0,    0,  232,    0,    0,    0,    0,
        0,  232,  232,  249,  249,    0,  249,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  249,    0,    0,    0,

        0,    0,    0,  249,  250,  250,    0,  250,    0,    0,
        0,  250,  250,  250,  250,    0,    0,  250,    0,    0,
        0,    0,  250,    0,    0,    0,  250,  254,  254,    0,
      254,  254,  264,    0,    0,  264,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  264,    0,    0,    0,    0,
        0,    0,    0,    0,  264,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  294,

      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  296,    0,    0,    0,  296,  296,  296,  296,  296,
      296,  296,  297,    0,    0,  297,    0,  297,  297,  297,
      297,  297,  297,  298,    0,    0,  298,  298,    0,  298,
      298,  298,  298,  298,  299,    0,    0,  299,  299,  299,
        0,  299,  299,  299,  299,  300,    0,    0,  300,  300,
      300,  300,    0,  300,  300,  300,  301,    0,    0,  301,
      301,  301,  301,  301,    0,  301,  301,  302,    0,    0,
      302,  302,  302,  302,  302,  302,    0,  302,  303,    0,

        0,  303,  303,  303,  303,  303,  303,  303,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  315,
      315,    0,  315,  315,  315,  315,  315,  315,  315,  315,
      316,  316,    0,  316,  316,  316,  316,  316,  316,  316,
      316,  317,  317,    0,  317,  317,  317,  317,  317,  317,
      317,  317,  318,  318,    0,  318,  318,  318,  318,  318,
      318,  318,  318,  319,  319,    0,  319,  319,  319,  319,
      319,  319,  319,  319,  320,  320,    0,  320,  320,  320,
      320,  320,  320,  320,  320,  321,  321,    0,  321,  321,

      321,  321,  321,  321,  321,  321,  322,  322,    0,  322,
      322,  322,  322,  322,  322,  322,  322,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  330,  330,  330,  330,  330,  330,

      330,  330,  330,  330,  330,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  333,    0,    0,
      333,  333,    0,  333,  333,  333,  333,  333,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/docmark_token_lexers.l"

































#line 955 "src/docmark_token_lexers.c"

#define INITIAL 0
#define LEX_ROOT 1
#define LEX_HEADING 2
#define LEX_ITALIC 3
#define LEX_BOLD 4
#define LEX_UNDERSCORE 5
#define LEX_STRIKETHROUGH 6
#define LEX_HIGHLIGHT 7
#define LEX_SUPERSCRIPT 8
#define LEX_SUBSCRIPT 9
#define LEX_BLOCKQUOTE 10
#define LEX_LIST_ELEMENT 11
#define LEX_DESCRIPTION_LIST_KEY 12
#define LEX_DESCRIPTION_LIST_VALUE 13
#define LEX_LINK 14
#define LEX_IMAGE 15
#define LEX_AUDIO 16
#define LEX_VIDEO 17
#define LEX_TOP_TITLED_TABLE 18
#define LEX_LEFT_TITLED_TABLE 19
#define LEX_TWO_WAY_TABLE 20
#define LEX_INFOBOX_TITLE 21
#define LEX_INFOBOX_CONTENT 22
#define LEX_FOOTNOTE_NOTE 23
#define LEX_ENDNOTE_NOTE 24
#define LEX_PARAGRAPH 25
#define LEX_INDENTED_PARAGRAPH 26
#define IN_RAW 27
#define IN_HEADING 28
#define IN_ITALIC 29
#define IN_BLOCKQUOTE 30
#define IN_CODE_BLOCK 31
#define IN_PARAGRAPH 32

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 87 "src/docmark_token_lexers.l"

#line 1209 "src/docmark_token_lexers.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 290 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1472 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 88 "src/docmark_token_lexers.l"
{ // RAW_DATA
	if (buffer_counter + 1 >= buffer_size) { // Check if buffer needs to be resized
		buffer_size = (buffer_size == 0) ? 1 : buffer_size * 2; // Double the buffer size
		buffer = realloc(buffer, buffer_size);
	}
	if (buffer == NULL) {
		fprintf(stderr, "ERROR: Memory allocation failed\n");
		exit(1);
	}

	buffer[buffer_counter++] = *yytext;
	buffer[buffer_counter] = '\0';
}
	YY_BREAK
case YY_STATE_EOF(LEX_HEADING):
case YY_STATE_EOF(LEX_PARAGRAPH):
#line 102 "src/docmark_token_lexers.l"
{ // RAW_DATA
	flush_buffer_raw();
	return 0;
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 107 "src/docmark_token_lexers.l"
{ // RAW_DATA
	flush_buffer_raw();
}
	YY_BREAK
case 3:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 111 "src/docmark_token_lexers.l"
{ // HORIZONTAL_RULE
	add_child(HORIZONTAL_RULE, NULL, NULL, 0, current_token);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 115 "src/docmark_token_lexers.l"
{ // Start Heading
	unsigned int rank = 0;
	while (*yytext == '#') {
		++rank;
		++yytext;
	}
	heading_rank = rank;

	LAST_CONDITION = YY_START;
	BEGIN(IN_HEADING);
}
	YY_BREAK
case 5:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 127 "src/docmark_token_lexers.l"
{ // HEADING with specified identifier
	char *identifier = strrchr(yytext, '{') + 1;
	char *identifier_end = identifier;
	char *data_end = identifier - 2;

	while (*identifier == ' ' || *identifier == '\t') {
		++identifier;
		++identifier_end;
	}
	++identifier_end;
	while (*identifier_end != ' ' && *identifier_end != '\t' && *identifier_end != '}') {
		++identifier_end;
	}
	while (*data_end == ' ' || *data_end == '\t') {
		--data_end;
	}

	*(++data_end) = '\0';
	*(identifier_end) = '\0';

	add_child(HEADING, strdup(yytext), strdup(identifier), heading_rank, current_token);

	BEGIN(LAST_CONDITION);
}
	YY_BREAK
case 6:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 152 "src/docmark_token_lexers.l"
{ // HEADING
	int len = strlen(yytext); // Strip trailing spaces from yytext
	while (len > 0 && (yytext[len - 1] == ' ' || yytext[len - 1] == '\t')) {
		yytext[len - 1] = '\0';
		len--;
	}

	add_child(HEADING, yytext, NULL, heading_rank, current_token);

	BEGIN(LAST_CONDITION);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 164 "src/docmark_token_lexers.l"
{ // Single character ITALIC
	flush_buffer_raw();
	yytext += 2;
	*yytext = '\0';
	--yytext;
	add_child(ITALIC, yytext, NULL, 0, current_token);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 172 "src/docmark_token_lexers.l"
{ // ITALIC
	flush_buffer_raw();
	char *data_pointer = yytext + 1;
	while (*data_pointer != '*') {
		++data_pointer;
	}
	*data_pointer = '\0';
	yyless(data_pointer - yytext + 1);
	add_child(ITALIC, yytext + 1, NULL, 0, current_token);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 183 "src/docmark_token_lexers.l"
{ // Single character BOLD
	flush_buffer_raw();
	yytext += 2;
	*yytext = '\0';
	--yytext;
	add_child(BOLD, yytext, NULL, 0, current_token);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 191 "src/docmark_token_lexers.l"
{ // BOLD
	flush_buffer_raw();
	char *data_pointer = yytext + 1;
	while (*data_pointer != '+') {
		++data_pointer;
	}
	*data_pointer = '\0';
	yyless(data_pointer - yytext + 1);
	add_child(BOLD, yytext + 1, NULL, 0, current_token);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 202 "src/docmark_token_lexers.l"
{ // Single character UNDERSCORE
	flush_buffer_raw();
	yytext += 2;
	*yytext = '\0';
	--yytext;
	add_child(UNDERSCORE, yytext, NULL, 0, current_token);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 210 "src/docmark_token_lexers.l"
{ // UNDERSCORE
	flush_buffer_raw();
	char *data_pointer = yytext + 1;
	while (*data_pointer != '~') {
		++data_pointer;
	}
	*data_pointer = '\0';
	yyless(data_pointer - yytext + 1);
	add_child(UNDERSCORE, yytext + 1, NULL, 0, current_token);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 221 "src/docmark_token_lexers.l"
{ // Single character STRIKETHROUGH
	flush_buffer_raw();
	yytext += 2;
	*yytext = '\0';
	--yytext;
	add_child(STRIKETHROUGH, yytext, NULL, 0, current_token);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 229 "src/docmark_token_lexers.l"
{ // STRIKETHROUGH
	flush_buffer_raw();
	char *data_pointer = yytext + 1;
	while (*data_pointer != '-') {
		++data_pointer;
	}
	*data_pointer = '\0';
	yyless(data_pointer - yytext + 1);
	add_child(STRIKETHROUGH, yytext + 1, NULL, 0, current_token);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 240 "src/docmark_token_lexers.l"
{ // Single character HIGHLIGHT
	flush_buffer_raw();
	yytext += 2;
	*yytext = '\0';
	--yytext;
	add_child(HIGHLIGHT, yytext, NULL, 0, current_token);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 248 "src/docmark_token_lexers.l"
{ // HIGHLIGHT
	flush_buffer_raw();
	char *data_pointer = yytext + 1;
	while (*data_pointer != '=') {
		++data_pointer;
	}
	*data_pointer = '\0';
	yyless(data_pointer - yytext + 1);
	add_child(HIGHLIGHT, yytext + 1, NULL, 0, current_token);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 259 "src/docmark_token_lexers.l"
{ // Single character SUPERSCRIPT
	flush_buffer_raw();
	yytext += 2;
	*yytext = '\0';
	--yytext;
	add_child(SUPERSCRIPT, yytext, NULL, 0, current_token);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 267 "src/docmark_token_lexers.l"
{ // SUPERSCRIPT
	flush_buffer_raw();
	char *data_pointer = yytext + 1;
	while (*data_pointer != '^') {
		++data_pointer;
	}
	*data_pointer = '\0';
	yyless(data_pointer - yytext + 1);
	add_child(SUPERSCRIPT, yytext + 1, NULL, 0, current_token);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 278 "src/docmark_token_lexers.l"
{ // Single character SUBSCRIPT
	flush_buffer_raw();
	yytext += 2;
	*yytext = '\0';
	--yytext;
	add_child(SUBSCRIPT, yytext, NULL, 0, current_token);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 286 "src/docmark_token_lexers.l"
{ // SUBSCRIPT
	flush_buffer_raw();
	char *data_pointer = yytext + 1;
	while (*data_pointer != '_') {
		++data_pointer;
	}
	*data_pointer = '\0';
	yyless(data_pointer - yytext + 1);
	add_child(SUBSCRIPT, yytext + 1, NULL, 0, current_token);
}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 297 "src/docmark_token_lexers.l"
{ // BLOCKQUOTE
	char *stripped_data = (char *) malloc((strlen(yytext) + 1) * sizeof(char));
	char *stripped_data_counter = stripped_data;

	while (*yytext == '>') {
		++yytext; // Consume the first `>`
		while (*yytext == ' ' || *yytext == '\t') {
			++yytext; // Consume whitespace
		}
		while (*yytext != '\n') {
			*stripped_data_counter = *yytext;
			++yytext;
			++stripped_data_counter;
		}
		*stripped_data_counter = *yytext;
		++yytext;
		++stripped_data_counter;
	}
	*(--stripped_data_counter) = '\0'; // Discard trailing newline

	add_child(BLOCKQUOTE, stripped_data, NULL, 0, current_token);
	free(stripped_data);
}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 321 "src/docmark_token_lexers.l"
{ // ORDERED_LIST		/* WARNING: Must change `{2,}` to `{TAB_SIZE,}` MANUALLY! */
	add_child(ORDERED_LIST, NULL, NULL, 0, current_token);
	Token *working_token = current_token->children[current_token->num_children - 1];

	char *stripped_data = (char *) malloc((strlen(yytext) + 1) * sizeof(char));
	char *stripped_data_counter = stripped_data;

	for (;;) {
		if (*yytext >= '0' && *yytext <= '9') {
			if (stripped_data_counter != stripped_data) { // Create token from last set of data
				*(--stripped_data_counter) = '\0'; // Discard trailing newline
				add_child(LIST_ELEMENT, stripped_data, NULL, 0, working_token);
				stripped_data_counter = stripped_data;
			}
			while (*yytext >= '0' && *yytext <= '9') {
				++yytext; // Consume the numerical signifier
			}
			++yytext; // Consume the period
			while (*yytext == ' ' || *yytext == '\t') {
				++yytext; // Consume whitespace
			}
			while (*yytext != '\n') {
				*stripped_data_counter = *yytext;
				++yytext;
				++stripped_data_counter;
			}
			*stripped_data_counter = *yytext;
			++yytext;
			++stripped_data_counter;
		}
		else if (*yytext == ' ' || *yytext == '\t') {
			unsigned int spacing = 0;
			while ((*yytext == ' ' || *yytext == '\t') && spacing < TAB_SIZE) {
				if (*yytext == ' ') {
					++spacing;
					++yytext;
				}
				else {
					spacing += TAB_SIZE;
					++yytext;
				}
			}
			while (*yytext != '\n') {
				*stripped_data_counter = *yytext;
				++yytext;
				++stripped_data_counter;
			}
			*stripped_data_counter = *yytext;
			++yytext;
			++stripped_data_counter;
		}
		else { // Create token from final set of data
			*(--stripped_data_counter) = '\0'; // Discard trailing newline
			stripped_data_counter = stripped_data;
			add_child(LIST_ELEMENT, stripped_data, NULL, 0, working_token);
			break;
		}
	}
}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 381 "src/docmark_token_lexers.l"
{ // UNORDERED_LIST		/* WARNING: Must change `{2,}` to `{TAB_SIZE,}` ! MANUALLY ! */
	add_child(UNORDERED_LIST, NULL, NULL, 0, current_token);
	Token *working_token = current_token->children[current_token->num_children - 1];

	char *stripped_data = (char *) malloc((strlen(yytext) + 1) * sizeof(char));
	char *stripped_data_counter = stripped_data;

	for (;;) {
		if (*yytext == '-') {
			if (stripped_data_counter != stripped_data) { // Create token from last set of data
				*(--stripped_data_counter) = '\0'; // Discard trailing newline
				add_child(LIST_ELEMENT, stripped_data, NULL, 0, working_token);
				stripped_data_counter = stripped_data;
			}
			++yytext; // Consume the signifying dash
			while (*yytext == ' ' || *yytext == '\t') {
				++yytext; // Consume whitespace
			}
			while (*yytext != '\n') {
				*stripped_data_counter = *yytext;
				++yytext;
				++stripped_data_counter;
			}
			*stripped_data_counter = *yytext;
			++yytext;
			++stripped_data_counter;
		}
		else if (*yytext == ' ' || *yytext == '\t') {
			unsigned int spacing = 0;
			while ((*yytext == ' ' || *yytext == '\t') && spacing < TAB_SIZE) {
				if (*yytext == ' ') {
					++spacing;
					++yytext;
				}
				else {
					spacing += TAB_SIZE;
					++yytext;
				}
			}
			while (*yytext != '\n') {
				*stripped_data_counter = *yytext;
				++yytext;
				++stripped_data_counter;
			}
			*stripped_data_counter = *yytext;
			++yytext;
			++stripped_data_counter;
		}
		else { // Create token from final set of data
			*(--stripped_data_counter) = '\0'; // Discard trailing newline
			stripped_data_counter = stripped_data;
			add_child(LIST_ELEMENT, stripped_data, NULL, 0, working_token);
			break;
		}
	}
}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 438 "src/docmark_token_lexers.l"
{ // DESCRIPTION_LIST
	add_child(DESCRIPTION_LIST, NULL, NULL, 0, current_token);
	Token *working_token = current_token->children[current_token->num_children - 1];

	while (*yytext != '\0') {
		if (*yytext == ':') {
			++yytext;
			while (*yytext == ' ' || *yytext == '\t') {
				++yytext;
			}
			char *data_pointer = yytext;
			while (*data_pointer != '\n') {
				++data_pointer;
			}
			*data_pointer = '\0';
			add_child(DESCRIPTION_LIST_VALUE, yytext, NULL, 0, working_token);
			yytext = ++data_pointer;
		}
		else {
			char *data_pointer = yytext;
			while (*data_pointer != '\n') {
				++data_pointer;
			}
			*data_pointer = '\0';
			add_child(DESCRIPTION_LIST_KEY, yytext, NULL, 0, working_token);
			yytext = ++data_pointer;
		}
	}
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 468 "src/docmark_token_lexers.l"
{ // Single character INLINE_CODE
	flush_buffer_raw();
	yytext += 2;
	*yytext = '\0';
	--yytext;
	add_child(INLINE_CODE, yytext, NULL, 0, current_token);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 476 "src/docmark_token_lexers.l"
{ // INLINE_CODE
	flush_buffer_raw();
	char *data_pointer = yytext + 1;
	while (*data_pointer != '`') {
		++data_pointer;
	}
	*data_pointer = '\0';
	yyless(data_pointer - yytext + 1);
	add_child(INLINE_CODE, yytext + 1, NULL, 0, current_token);
}
	YY_BREAK
case 27:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 488 "src/docmark_token_lexers.l"
{ // Start CODE_BLOCK
	yytext += 2;
	add_child(START_CODE_BLOCK, yytext, NULL, 0, current_token);
	BEGIN(IN_CODE_BLOCK);
}
	YY_BREAK
case 28:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 494 "src/docmark_token_lexers.l"
{ // End CODE_BLOCK
	add_child(END_CODE_BLOCK, NULL, NULL, 0, current_token);
	BEGIN(LEX_ROOT);
}
	YY_BREAK
case 29:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 499 "src/docmark_token_lexers.l"
{
	char *data = malloc(strlen(yytext) + 2);
	strcpy(data, yytext);
	strcat(data, "\n");
	add_child(RAW_DATA, data, NULL, 0, current_token);
	free(data);
}
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 507 "src/docmark_token_lexers.l"
{
	yyless(1);
	add_child(RAW_DATA, "\n", NULL, 0, current_token);
}
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 512 "src/docmark_token_lexers.l"
{}
	YY_BREAK
// TOP_TITLED_TABLE

// LEFT_TITLED_TABLE

// TWO_WAY_TABLE

case 32:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 523 "src/docmark_token_lexers.l"
{ // LEFT_COLUMN
	if (in_left_column || in_right_column) {
		add_child(PARAGRAPH, yytext, NULL, 0, current_token);
	} else {
		add_child(LEFT_COLUMN, NULL, NULL, 0, current_token);
	}
	in_left_column = 1;
}
	YY_BREAK
case 33:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 532 "src/docmark_token_lexers.l"
{ // DIVIDER_COLUMN
	if (!in_left_column || in_right_column) {
		add_child(PARAGRAPH, yytext, NULL, 0, current_token);
	} else {
		add_child(DIVIDER_COLUMN, NULL, NULL, 0, current_token);
	}
	in_left_column = 0;
	in_right_column = 1;
}
	YY_BREAK
case 34:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 542 "src/docmark_token_lexers.l"
{ // RIGHT_COLUMN
	if (in_left_column || !in_right_column) {
		add_child(PARAGRAPH, yytext, NULL, 0, current_token);
	} else {
		add_child(RIGHT_COLUMN, NULL, NULL, 0, current_token);
	}
	in_right_column = 0;
}
	YY_BREAK
// INFOBOX_TITLE

// INFOBOX_CONTENT

// FOOTNOTE_NOTE

// ENDNOTE_NOTE

case 35:
YY_RULE_SETUP
#line 563 "src/docmark_token_lexers.l"
{ // PARAGRAPH
	if (buffer_counter + 1 >= buffer_size) { // Check if buffer needs to be resized
		buffer_size = (buffer_size == 0) ? 1 : buffer_size * 2; // Double the buffer size
		buffer = realloc(buffer, buffer_size);
	}
	if (buffer == NULL) {
		fprintf(stderr, "ERROR: Memory allocation failed\n");
		exit(1);
	}

	buffer[buffer_counter++] = *yytext;
	buffer[buffer_counter] = '\0';
}
	YY_BREAK
case YY_STATE_EOF(LEX_ROOT):
case YY_STATE_EOF(LEX_LIST_ELEMENT):
#line 577 "src/docmark_token_lexers.l"
{ // PARAGRAPH
	flush_buffer_paragraph();
	return 0;
}
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 582 "src/docmark_token_lexers.l"
{ // PARAGRAPH
	flush_buffer_paragraph();
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 587 "src/docmark_token_lexers.l"
{
	printf("UNHANDLED: %c\n", *yytext);
}
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 591 "src/docmark_token_lexers.l"
{
	printf("UNHANDLED: %c", *yytext);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 594 "src/docmark_token_lexers.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1926 "src/docmark_token_lexers.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(LEX_ITALIC):
case YY_STATE_EOF(LEX_BOLD):
case YY_STATE_EOF(LEX_UNDERSCORE):
case YY_STATE_EOF(LEX_STRIKETHROUGH):
case YY_STATE_EOF(LEX_HIGHLIGHT):
case YY_STATE_EOF(LEX_SUPERSCRIPT):
case YY_STATE_EOF(LEX_SUBSCRIPT):
case YY_STATE_EOF(LEX_BLOCKQUOTE):
case YY_STATE_EOF(LEX_DESCRIPTION_LIST_KEY):
case YY_STATE_EOF(LEX_DESCRIPTION_LIST_VALUE):
case YY_STATE_EOF(LEX_LINK):
case YY_STATE_EOF(LEX_IMAGE):
case YY_STATE_EOF(LEX_AUDIO):
case YY_STATE_EOF(LEX_VIDEO):
case YY_STATE_EOF(LEX_TOP_TITLED_TABLE):
case YY_STATE_EOF(LEX_LEFT_TITLED_TABLE):
case YY_STATE_EOF(LEX_TWO_WAY_TABLE):
case YY_STATE_EOF(LEX_INFOBOX_TITLE):
case YY_STATE_EOF(LEX_INFOBOX_CONTENT):
case YY_STATE_EOF(LEX_FOOTNOTE_NOTE):
case YY_STATE_EOF(LEX_ENDNOTE_NOTE):
case YY_STATE_EOF(LEX_INDENTED_PARAGRAPH):
case YY_STATE_EOF(IN_RAW):
case YY_STATE_EOF(IN_HEADING):
case YY_STATE_EOF(IN_ITALIC):
case YY_STATE_EOF(IN_BLOCKQUOTE):
case YY_STATE_EOF(IN_CODE_BLOCK):
case YY_STATE_EOF(IN_PARAGRAPH):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 290 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 290 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 289);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 594 "src/docmark_token_lexers.l"


static void lex(int mode, Token *token) {
	size_t input_size = strlen(token->data);
	char *input = (char *) malloc((input_size + 2) * sizeof(char));
	strcpy(input, token->data);
	input[input_size] = '\n';
	input[input_size + 1] = '\0';

	yyin = fmemopen(input, strlen(token->data), "r");
	current_token = token;

	BEGIN(mode);
	yylex();

	free(token->data);
	free(input);
	token->data = NULL;
	mark_raw(token);
}

int lex_root(Token *token) {
	lex(LEX_ROOT, token);
}

int lex_heading(Token *token) {
	lex(LEX_HEADING, token);
}

int lex_italic(Token *token) {
	lex(LEX_ITALIC, token);
}

int lex_bold(Token *token) {
	lex(LEX_BOLD, token);
}

int lex_underscore(Token *token) {
	lex(LEX_UNDERSCORE, token);
}

int lex_strikethrough(Token *token) {
	lex(LEX_STRIKETHROUGH, token);
}

int lex_highlight(Token *token) {
	lex(LEX_HIGHLIGHT, token);
}

int lex_superscript(Token *token) {
	lex(LEX_SUPERSCRIPT, token);
}

int lex_subscript(Token *token) {
	lex(LEX_SUBSCRIPT, token);
}

int lex_blockquote(Token *token) {
	lex(LEX_BLOCKQUOTE, token);
}

int lex_list_element(Token *token) {
	lex(LEX_LIST_ELEMENT, token);
}

int lex_description_list_key(Token *token) {
	lex(LEX_DESCRIPTION_LIST_KEY, token);
}

int lex_description_list_value(Token *token) {
	lex(LEX_DESCRIPTION_LIST_VALUE, token);
}

int lex_link(Token *token) {
	lex(LEX_LINK, token);
}

int lex_image(Token *token) {
	lex(LEX_IMAGE, token);
}

int lex_audio(Token *token) {
	lex(LEX_AUDIO, token);
}

int lex_video(Token *token) {
	lex(LEX_VIDEO, token);
}

int lex_top_titled_table(Token *token) {
	lex(LEX_TOP_TITLED_TABLE, token);
}

int lex_left_titled_table(Token *token) {
	lex(LEX_LEFT_TITLED_TABLE, token);
}

int lex_two_way_table(Token *token) {
	lex(LEX_TWO_WAY_TABLE, token);
}

int lex_infobox_title(Token *token) {
	lex(LEX_INFOBOX_TITLE, token);
}

int lex_infobox_content(Token *token) {
	lex(LEX_INFOBOX_CONTENT, token);
}

int lex_footnote_note(Token *token) {
	lex(LEX_FOOTNOTE_NOTE, token);
}

int lex_endnote_note(Token *token) {
	lex(LEX_ENDNOTE_NOTE, token);
}

int lex_paragraph(Token *token) {
	lex(LEX_PARAGRAPH, token);
}

int lex_indented_paragraph(Token *token) {
	lex(LEX_INDENTED_PARAGRAPH, token);
}

int lex_(Token *token) {
	// printf("WARNING: Token is not being lexed: uses `lex_()` as lexing function\n");
	// print_token("", token);
	return 0;
}
